def get_client_around_me(): pass
def create_profile(name, location, details, opening_hours): pass
def update_profile(): pass
def delete_profile(): pass
def update_status(): pass
def create_menu(): pass
def update_menu(): pass
def search_item(): pass
def create_item(): pass
def update_item(): pass
def get_queue(): pass
def get_next_to_serve(): pass
def get_queue_update(): pass
def create_barman(): pass
def update_barman(): pass
def update_barman_status(): pass
def create_shift(): pass
def addTo_shift(): pass
def remove_to_shift(): pass
def update_work_flow(): pass
