# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNN_ClientMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, through='client.RNN_MenuItem', to='client.Item'),
        ),
        migrations.AlterField(
            model_name='rnn_menuitem',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.Item'),
        ),
        migrations.AddField(
            model_name='rnn_clientmenu',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
        migrations.AddField(
            model_name='rnn_clientmenu',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.Menu'),
        ),
        migrations.AddField(
            model_name='client',
            name='menus',
            field=models.ManyToManyField(blank=True, through='client.RNN_ClientMenu', to='client.Menu'),
        ),
    ]
