 version: '3'
 services:
   db:
     image: 127.0.0.1:5000/clientroot_db
     build:
      context: .
      dockerfile: Dockerfile-mysql
     ports:
      - 3306
     volumes:
       - .:/code

   web:
     image: 127.0.0.1:5000/clientroot_web
     command: bash ./docker-entrypoint.sh
     build:
      context: .
      dockerfile: Dockerfile
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     deploy:
       replicas: 2
       restart_policy:
        condition: on-failure
