FROM django

COPY /clientroot /clientroot

WORKDIR /clientroot

RUN pip install -r requirements.txt

RUN python manage.py runserver 127.0.0.0:8000

#WORKDIR /

#ENTRYPOINT ["/docker-entrypoint.sh"]

#CMD [ "python", "~/manage.py runserver 127.0.0.0:8000" ]
#CMD [ "echo", "%PATH%" ]