 version: '3'
 services:
   db:
     image: postgres
     environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

   web:
     image: 127.0.0.1:5000/clientroot_web
     build: ./web
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./web:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     deploy:
       replicas: 2