 version: '3'
 services:
   db:
     image: postgres
     environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=client_db
        - PGDATA=/var/lib/postgresql/data/client
     deploy:
       placement:
         constraints: [node.role == manager]
         
   web:
     image: 127.0.0.1:5000/clientroot_web
     build: ./web
     command: bash ./starter.sh
     volumes:
       - ./web:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     deploy:
       replicas: 2